name: Create Release Candidate
on:
  workflow_dispatch:
    inputs:
      from_ref: { description: "Upstream FROM ref", required: true }
      to_ref:   { description: "Upstream TO ref",   required: true }
permissions: { contents: write }

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: "11" }

      - name: Fetch upstream (old/new)
        run: |
          bash .github/tools/fetch-upstream-msq.sh "${{ inputs.from_ref }}" ".sync/old"
          bash .github/tools/fetch-upstream-msq.sh "${{ inputs.to_ref   }}" ".sync/new"

      - name: Overlay into repo src (auto except owned)
        run: |
          set -e
          SRC=".sync/new/extensions-core/multi-stage-query"
          [ -d "$SRC/src" ] || { echo "No src/ under $SRC"; exit 2; }
          rsync -a --delete --exclude '.git' \
            --exclude-from=.github/sync/auto_merge_restricted.txt \
            --include='src/' --include='src/**' --exclude='*' \
            "$SRC/" .
          git status -s | sed -n '1,100p'

      - name: Generate manual-port report (owned + changed)
        run: |
          bash .github/tools/generate-sync-report.sh \
            ".sync/old/extensions-core/multi-stage-query" \
            ".sync/new/extensions-core/multi-stage-query" > sync-report.md
          sed -n '1,120p' sync-report.md

      - name: Commit to release-candidate
        run: |
          set -e
          git config --local user.name  "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          BR="${{ inputs.to_ref }}-rc"
          git checkout -B "$BR"
          git add -A src sync-report.md
          if git diff --cached --quiet; then
            echo "No changes staged"; exit 3
          fi
          git commit -m "Auto-generated release candidate @${{ inputs.to_ref }} + report"
          git push -u origin "$BR"
